[package]
name = "soprox"
version = "0.0.1"
description = "A Rust-based Solana program boilerplate"
authors = ["Tu Phan <tuphan@descartes.network>"]
license = "MIT"
edition = "2018"

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]
byteorder = "1.3"
solana-sdk = { version = "=1.3.9", default-features = false, optional = true }

[lib]
name = "soprox"
crate-type = ["cdylib", "lib"]
